create or replace TABLE MY_SURVEY (
	REPORT_YEAR NUMBER(38,0),
	INDUSTRY_CODE VARCHAR(10),
	INDUSTRY_NAME VARCHAR(255),
	ENTERPRISE_SIZE VARCHAR(50),
	FINANCIAL_VARIABLE VARCHAR(255),
	VARIABLE_VALUE NUMBER(38,2),
	UNIT_OF_MEASURE VARCHAR(50)
);

create or replace TABLE STG_SURVEY (
	REPORT_YEAR NUMBER(38,0),
	INDUSTRY_CODE VARCHAR(10),
	INDUSTRY_NAME VARCHAR(255),
	ENTERPRISE_SIZE VARCHAR(50),
	FINANCIAL_VARIABLE VARCHAR(255),
	VARIABLE_VALUE NUMBER(38,2),
	UNIT_OF_MEASURE VARCHAR(50)
);