name: Deploy Snowflake to QA

on:
  push:
    branches: [ "main" ]

jobs:
  flyway-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Flyway
      run: |
        wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.10.0/flyway-commandline-10.10.0-linux-x64.tar.gz | tar xvz
        sudo ln -s $(pwd)/flyway-10.10.0/flyway /usr/local/bin/flyway
        flyway -v   # verify installation

    - name: Run Flyway Migration on QA
      run: |
        flyway \
        -url="jdbc:snowflake://${{ secrets.SNOWFLAKE_ACCOUNT }}.snowflakecomputing.com/?db=CENTRAL_DATA_REPORTING&schema=DEV&warehouse=COMPUTE_WH&role=DEVELOPER_ROLE" \
        -user="${{ secrets.SNOWFLAKE_DEV_USER }}" \
        -password="${{ secrets.SNOWFLAKE_DEV_PASSWORD }}" \
        -locations="filesystem:sql" \
        migrate
