name: Deploy Snowflake to QA

on:
  push:
    branches: [ "main" ]

jobs:
  flyway-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Flyway
      run: |
        wget -qO flyway.tar.gz https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.15.2/flyway-commandline-10.15.2-linux-x64.tar.gz
        tar -xzf flyway.tar.gz
        sudo ln -s $(pwd)/flyway-10.15.2/flyway /C:/flyway-12.4.0/db_dev
        flyway -v 

    - name: Run Flyway Migration on QA
      run: |
        ./flyway/flyway \
          -url="jdbc:snowflake://${{ secrets.SNOWFLAKE_ACCOUNT }}.snowflakecomputing.com/?db=CENTRAL_DATA_REPORTING&schema=DEV&warehouse=COMPUTE_WH&role=DEVELOPER_ROLE" \
          -user="${{ secrets.SNOWFLAKE_USER }}" \
          -password="${{ secrets.SNOWFLAKE_PASSWORD }}" \
          -locations="filesystem:sql" \
          migrate
